service: ms-node-user-serverless
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  region: sa-east-1
  memorySize: 256
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

functions:
  user-save:
    handler: src/presentation/routes/user-save-post.main
    timeout: 30
    events:
      - http:
          method: post
          path: /user
  user-update:
    handler: src/presentation/routes/user-update-put.main
    timeout: 30
    events:
      - http:
          method: put
          path: /user/{id}
  user-view:
    handler: src/presentation/routes/user-view-get.main
    timeout: 30
    events:
      - http:
          method: get
          path: /user/{id}
package:
  individually: true
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    external:
      - "pg-native"
    target: "node16"
    define: { "require.resolve": undefined }
    platform: "node"
    concurrency: 10
    watch:
      pattern: ["src/**/*.ts"]
      ignore: [".serverless/**/*", ".esbuild", "dist", "node_modules"]
